# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="bira"

## oh-my-zsh configuration
COMPLETION_WAITING_DOTS="true"

# Plug-ins
plugins=(git)

# completions
export FPATH=$HOME/.completion/zsh:$FPATH

source $ZSH/oh-my-zsh.sh

autoload -U colors; colors

# User configuration
if command -v direnv >/dev/null 2>&1; then
  # load direnv
  eval "$(direnv hook zsh)"
fi

# Load aliases
. <(cat $HOME/.aliases/*.alias)

# Load OS specific environments
if [[ "$(uname)" == "Darwin" ]]; then
    . $HOME/.env/os/macos.env
fi

# Load environment variables
. <(cat $HOME/.env/*.env)

# Key binds
bindkey "^k" history-beginning-search-backward
bindkey "^j" history-beginning-search-forward


