---
- name: Check if Go version {{ item }} is installed
  stat:
    path: "{{ gvm_root }}/gos/go{{ item }}"
  register: go_check
  tags: ["go"]

- name: Install Go version {{ item }} using gvm
  shell: "source {{ gvm_root }}/scripts/gvm && gvm install go{{ item }}"
  when: not go_check.stat.exists
  tags: ["go"]
