---
- name: Configure personal machine.
  connection: local
  hosts:
    - macos
  vars_files:
    - vars/homebrew.yaml
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
      vars:
        homebrew_installed_packages: "{{ hostvars[inventory_hostname].homebrew_apps + homebrew_apps }}"
        homebrew_cask_apps: "{{ hostvars[inventory_hostname].homebrew_casks + homebrew_casks }}"
    - role: go
